#include "stdafx.h"
#include "CppUnitTest.h"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

#include "..\Student\Ucn.h"

namespace PersonTest
{
	/// Valid UCNs generated by http://georgi.unixsol.org/programs/egn.php
	TEST_CLASS(UcnTest)
	{
		void AssertUcnProperties(const Ucn& obj, int Day, int Month, int Year, bool IsMale, bool IsDateCorrect, bool IsChecksumCorrect, bool IsValid)
		{
			Assert::AreEqual(obj.GetDay(), Day, L"Day");
			Assert::AreEqual(obj.GetMonth(), Month, L"Month");
			Assert::AreEqual(obj.GetYear(), Year, L"Year");
			Assert::AreEqual(obj.IsMale(), IsMale, L"IsMale");
			Assert::AreEqual(obj.IsFemale(), !IsMale, L"IsFemale");
			Assert::AreEqual(obj.VerifyDate(), IsDateCorrect, L"IsDateCorrect");
			Assert::AreEqual(obj.VerifyChecksum(), IsChecksumCorrect, L"IsChecksumCorrect");
			Assert::AreEqual(obj.IsValid(), IsValid, L"IsValid");
		}

		TEST_METHOD(Ucn_Correct19Century)
		{
			AssertUcnProperties(Ucn(5023123363), 12, 3, 1850, true, true, true, true);
			AssertUcnProperties(Ucn(5022284810), 28, 2, 1850, false, true, true, true);
		}

		TEST_METHOD(Ucn_Correct20Century)
		{
			AssertUcnProperties(Ucn(1805122980), 12, 5, 1918, true, true, true, true);
			AssertUcnProperties(Ucn(5712131070), 13, 12, 1957, false, true, true, true);
		}

		TEST_METHOD(Ucn_Correct21Century)
		{
			AssertUcnProperties(Ucn(5050062163), 6, 10, 2050, true, true, true, true);
			AssertUcnProperties(Ucn(5049142391), 14, 9, 2050, false, true, true, true);
		}

		TEST_METHOD(Ucn_Incorrect)
		{
			// incorrect date, correct checksum
			AssertUcnProperties(Ucn(5063123362), 12, 3, 2050, true, false, true, false);

			// correct date, incorrect checksum
			AssertUcnProperties(Ucn(5050062161), 6, 10, 2050, true, true, false, false);
		}
	};
}